channels:
  - conda-forge
dependencies:
  # Jupyter
  - jupyterlab=2
  - nodejs
  - nbconvert=5.5
  - widgetsnbextension=3.5
  # Python Kernel
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - tensorflow
  - tensorflow-gpu
